# Generated by Django 6.1.1 on 2026-09-06 13:11

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_default_users(apps, schema_editor):
    User = apps.get_model('app', 'User')

    default_users = [
        {
            "username": "user1",
            "email": "user1@tasks.local",
            "password": make_password("123"),
            "is_staff": False,
            "is_superuser": False
        },
        {
            "username": "user2",
            "email": "user2@tasks.local",
            "password": make_password("123"),
            "is_staff": False,
            "is_superuser": False
        }
    ]

    for user_data in default_users:
        User.objects.create(**user_data)


def remove_default_users(apps, schema_editor):
    User = apps.get_model('app', 'User')
    User.objects.filter(username__in=["staff_member", "regular_user"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0001_initial'),  # Crucial: Must wait until Django's auth system is ready
    ]

    operations = [
        migrations.RunPython(create_default_users, reverse_code=remove_default_users),
    ]
